services:
  archive:
    build: "."
    init: true
    env_file:
      - path: .env
        required: false
    ports:
      - "8000:8000"
    volumes:
      - "./public:/public:ro"
    develop:
      watch:
        - path: "."
          action: "sync+restart"
          target: "/app"
        - path: "package.json"
          action: "rebuild"
